# Generated by Django 6.0.2 on 2026-03-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Voter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("last_name", models.TextField()),
                ("first_name", models.TextField()),
                ("street_number", models.TextField()),
                ("street_name", models.TextField()),
                ("apt", models.TextField(blank=True)),
                ("zip_code", models.TextField()),
                ("dob", models.DateField()),
                ("date_registered", models.DateField()),
                ("party", models.CharField(max_length=5)),
                ("precinct", models.CharField(max_length=10)),
                ("v20state", models.BooleanField(default=False)),
                ("v21town", models.BooleanField(default=False)),
                ("v21primary", models.BooleanField(default=False)),
                ("v22general", models.BooleanField(default=False)),
                ("v23town", models.BooleanField(default=False)),
                ("voter_score", models.IntegerField(default=0)),
            ],
        ),
    ]
