# Generated by Django 6.0.2 on 2026-03-03 15:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mini_insta", "0002_post_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="photo",
            name="image_file",
            field=models.ImageField(blank=True, upload_to="mini_insta/"),
        ),
    ]
