# Generated by Django 6.0.3 on 2026-04-21 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("students", models.FloatField(default=0)),
                ("capacity", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("surname", models.TextField()),
                ("image_file", models.ImageField(upload_to="project/")),
            ],
        ),
        migrations.CreateModel(
            name="Dorm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField()),
                ("address", models.TextField()),
                ("image_url", models.TextField()),
                ("capacity", models.FloatField()),
                ("current_size", models.FloatField(default=0)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.department",
                    ),
                ),
                (
                    "resident_assistant",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="project.professor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="department",
            name="staff",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.professor",
            ),
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.TextField()),
                ("last_name", models.TextField()),
                ("course_program", models.TextField()),
                ("hometown", models.TextField()),
                (
                    "lives_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="project.dorm"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Hatred",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="first_hatred",
                        to="project.student",
                    ),
                ),
                (
                    "second_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="second_hatred",
                        to="project.student",
                    ),
                ),
            ],
        ),
    ]
