# Generated by Django 6.0.3 on 2026-04-21 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0002_professor_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dorm",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.department",
            ),
        ),
        migrations.AlterField(
            model_name="dorm",
            name="resident_assistant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.professor",
            ),
        ),
    ]
