# Generated by Django 6.0.3 on 2026-04-21 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project", "0003_alter_dorm_department_alter_dorm_resident_assistant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="course_program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.department",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="lives_in",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="project.dorm",
            ),
        ),
    ]
